<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!doctype html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Harvest &amp; Home</title><link rel="stylesheet" href="/resources/storefront.css"></head>
<body><div class="site-shell">
<header class="topbar"><a class="brand" href="/"><span class="brand-mark">+</span> Harvest &amp; Home</a><nav class="nav-links" aria-label="Main navigation"><a href="/user/products">Shop</a><a href="/profileDisplay">Profile</a><a href="/logout">Log out</a></nav></header>
<main class="page-width"><section class="hero"><div><span class="eyebrow">Good food, close to home</span><h1>Fresh finds for everyday living.</h1><p>Thoughtfully sourced pantry staples and seasonal goods, selected to make your kitchen feel a little more alive.</p><a class="button" href="/user/products">Explore the shop</a></div><div class="hero-art" aria-hidden="true"></div></section>
<div class="section-heading"><h2>From the shelves</h2><a href="/user/products">View all products &rarr;</a></div>
<c:choose><c:when test="${not empty products}"><div class="product-grid"><c:forEach var="product" items="${products}" begin="0" end="3"><article class="product-card"><div class="product-image"><img src="${product.image}" alt="${product.name}"></div><div class="product-info"><h3>${product.name}</h3><p class="product-meta">${product.category.name}<br>${product.description}</p><span class="price">$${product.price}</span><form action="/cart/add" method="post" style="margin-top:14px"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"><input type="hidden" name="productId" value="${product.id}"><button class="button button-light" type="submit">Add to cart</button></form></div></article></c:forEach></div></c:when><c:otherwise><p class="form-note">${msg}</p></c:otherwise></c:choose></main>
<footer class="footer">Harvest &amp; Home &middot; Everyday goods, thoughtfully chosen.</footer></div></body></html>